const allShayari = [
    // --- Nayi Shayari Sabse Upar Yahan Likhein ---
    " "
    
    // --- Aapka Purana Sara Data Niche Hai ---
    "बेशक तुम जा चुके हो, पर तुम्हारा नाम आज भी, मेरे दिल की धड़कने तेज कर देता है।",
    "अरे aapko to इज़्ज़त krni chahiye thi is खामोशी ki..! Hm to iske phichhe aapki औकात छिपाये baithe the..!!",
    "Mere pass Aana to Waqt nikal kar aana Kyunki mere pass baten bahut hain aur sunane wale koi nhi.",
    "Kuchh लोगों Ne हमें Aise समय per धोखा Diya..! Jab हम Kisi Se Unki wafadari ki बातें kar रहे the..!!",
    "Khatm kar diya unhone bhi is Sal Rishte jinhone Jindagi Bhar Sath nibhaane ke vade kiye the.",
    "Bichhadne ki jaldi unhen Thi Aur Ilzaam Sara Ham per Lagaya Gaya.",
    "Safar tumhare sath Chhota Raha lekin Jindagi Bhar Ke Liye Sabak ban gaya.",
    "Shant chehron Ke Piche Aksar ghav Gehra Hote Hain.",
    "Uski Khushi Ke Liye use to Chhod Diya Maine per Meri Khushiyan bhi Usi ke sath Chali gai.",
    "Vah bhul gaye Hamen Kisi Ki Khatir To Kya Hua Ham bhi to Unki Khatir Jamana bhulaye Baithe the.",
    "Jao Maaf Kiya Tumhen Aane Wale Waqt Mein Khuda Tumhare bete ko Tumhare Jaisi Ladki Se Bachaye.",
    "Hamen to kab se Pata Tha Ki Tum Bewafa Ho Tumhen Chaha isliye ki Shayad Tumhari fitrat Badal Jaaye.",
    "Unhen Mil Hi Jaate Hain Koi Na Koi jinhen acche kirdar Nahin sirf kiraedar chahie Hote Hain.",
    "Kabhi Maaf nahin kar Paunga usko Jisne bewajah Meri Jindagi ko तहस-नहस karke rakh Diya.",
    "Ek din khatm ho hi Jaenge ya to Gam nhi to FIR ham.",
    "Jindagi Mein Ek Aisa Insan Jarur Hona chahie Jo HAL Puche To Sach bataya Ja sake.",
    "Ek Din Tumhare Karam Tumse milane aaenge Meri Jaan Bus use Din Tumhara Mat Hona.",
    "Bewafa hi nahi berham bhi ho tum Jindagi tabah Karke Kahate Ho ki jao ab khush raho tum.",
    "Tum apna Charitra Kitna bhi saaf Rakh Lo lekin chhodane wala Koi Na Koi Galti nikal hi dega.",
    "Kya fayda ab nishaniyan Dekhkar Rone Se Jab Sath the tab Kadar Ki Na Gai.",
    "Yah Mujhse Ek Ladki Nahin Bulai Jari aur log pata nahin Kaise kah Dete Hain Ki 36 aaenge 36 Jaenge.",
    "Sach Sach batana Puri koshish kar rahe ho na use Bhulane ki.",
    "Main Shayad ab Tumhari Soch Mein Bhi Nahin Aur Tu Mujhe लफ़्ज़-लफ़्ज़ Yad hai.",
    "Kuchh pal ke liye Laga tha ki Hamari Kahani bhi shaadi Tak pahunchegi Pal Bhar Mein Sab tabah Kar Diya Usne Kisi Aur Kaha Tham kar.",
    "Pal Bhar Ke Liye chahie tha unhen Sath aur Hamen Laga Jindagi Bhar Ke Liye Humsafar Mil Gaya.",
    "Kahana To Nahin chahie per kasam se bahut Pareshan hun Kahin Kuchh kar lun to Maaf Karna.",
    "क्यूँ महसूस नहीं हुई उन्हें हमारी तकलीफ जो कभी कहते थे ki हम तुम्हें तुमसे ज्यादा जानते हैं.",
    "Unhen Chahat hi nahin Thi Kabhi Hamari unhen to Hamari sirf jarurat thi.",
    "Pahli bar Kisi Se Pyar hua tha aur vahi Bewafa nikal gai.",
    "Hans kar Bhul Jaate Hain sari baten iska matlab yah Nahin ki baten Hain Dil per Nahin Lagti.",
    "Tere Jaane ka itna Dukh Nahin Dukh to sirf is baat ka Hai Ki Itna Pyar karne ke bad Bhi To Bewafa nikal gai.",
    "Tum Nahin Laga paoge andaza Meri tabahi ka Tumne Sham Hone ke bad Mujhe Dekha hi kahan hai.",
    "ना तुमने कभी समझ और ना समझना चाहा नहीं तो मैं पागल चाहता ही क्या था तुमसे तुम्हारे अलावा.",
    "पहले स्त्रियाँ भले ही कमजोर थी लेकिन वफादार थी अब स्त्रियाँ मजबूत है लेकिन वफादार नहीं.",
    "दगा देने से पहले इक पल के लिए खुदा से डर गए होते.. या फिर दग़ा देने से पहले या तो तुम, या दगा खाने से पहले हम मर गए होते.",
    "टूटे हम, धोखा हमे मिला, तमाशा हमारा बना, तन्हा हम हुए, तो फिर बर्बाद आप कैसे हुए.",
    "वो जो सच्चाई से मोहब्बत निभा सकते थे उन्हें मोहब्बत कभी मिली ही नहीं.",
    "हर बात भूल जाया करते थे हम, Pr tera Mujhe ek ek lafz Yaad Hai",
    "गलत नहीं हुआ मेरे साथ, मैने वफादारी की है तो सजा मिलना तो लाजमी tha...",
    "किसी की feelings के साथ इतना भी मत खेलो की वह फिर कभी किसी पर भरोसा ही ना कर Paye",
    "Mahadev, pls help me. Before, I do something wrong to myself..",
    "गलतफहमी में मत रहना मेरी जान.. किस्मत हर बार हर किसी को दूसरा मौका नहीं देती....",
    "ढेर सारी मोहब्बत वार दी जिस पर हमने, मिट्टी बराबर भी कदर नहीं की उसने.",
    "Time paas वाले नही है हम जिंदगी भर साथ निभा सको, तभी हाथ आगे बढ़ाना....",
    "मेरी उदासियाँ तुम्हे कैसे नज़र आतीं, तुम्हे तो देखते ही हम मुस्कुराने लगते थे...",
    "बहुत ख्याल रखते हैं वो अपने दिल का, इधर नहीं लगता तो, उधर लगा लेते हैं बात गहरी है फिर से पढ़ो....",
    "धरी की धरी रह गई सारी कसमें, वो मजबूरी का नाम देकर दूर हो गए हमसे...",
    "कुछ ऐसी बातें बोली थी उसने कि फिर मुझे अपनी पसंद से नफरत हो गयी..",
    "ye जिस जगह लाकर तुमने छोड़ा है, तमाम उम्र निकल जायेगी यहाँ से निकलने में..",
    "मोहब्बत में मर्जियां नहीं चलती साहब, गर्दने झुकाई जाती हैं हुकुम-ए-यार पर...",
    "क्यूँ झूठ बोले कि भूल गए तुम्हें, तुम आज भी याद आते हो और बहुत याद आते हो",
    "आज कोई अचानक मुझसे लिपट कर बहुत रोया.. एहसास हुआ की यह तो मेरा ही साया था...",
    "मैं भी रह चुका हूँ अज़ीज़ किसी का.... मैं बकिफ हूँ इस चार दिन की मोहब्बत से..",
    "उसने कहा तुमसे मिलना जिंदगी की सबसे बड़ी गलती थी और मुझे याद है वो दिन जब उस ने कहा था कि काश हम पहले मिले होते",
    "अचानक से बदल जाने वाली वो लड़की... कभी पागल थी मेरे लिए",
    "लोग अक्सर मुझ से पूछते है कि जब वो गया, तुम रोये तो बहुत होगे.. मै मुस्कुरा कर कह देता कि वो गया ही कहा है अभी",
    "तुम खुश रहो अपने नये यार के साथ, हम तो Yadon Ke Sahare ही ji Lenge..",
    "जिसको जितनी शिद्दत से चाहोगे, वह उतनी ही बेरहमी से तुम्हारा दिल दुखायेगा",
    "मैं बुलंद हौंसले वाला ज़िदी सा लड़का, रोज तेरी यादों से लड़ता और रो देता हूँ..",
    "औकात नहीं थी जमाने में, जो मेरी कीमत लगा सके.. कम्बख्त इश्क में क्या गिरे मुफ्त में नीलाम हो गए..",
    "मुझे कभी प्यार ही नहीं मिला, ऐसा बोलकर रोने वाली लड़कियाँ किसी एक लड़के को जिंदा लाश बनाकर छोड़ चुकी होतीं हैं..",
    "बता देना सबको कि तूने धोखे से हराया है मुझे, वरना मेने कोई कसर नही छोड़ी थी तुझसे प्यार करने में.",
    "मैं डरता रहा लोगों को खोने से, अब तन्हा हूँ तो समझ आया कि मुझे खोने का डर तो किसी को ना था...",
    "वजह चाहे कुछ भी हो, धोख़ा धोख़ा ही होता है",
    "ठंडा मौसम हल्की सी बारिश, हाथों में मेरे उसका हाथ था, चार कदम साथ चले, आँख खुली तो यह ख्वाब था",
    "After a long time I saw her photo with me and I realized, कि कभी कभी धोख़ा भी कितना खूबसूरत होता है",
    "धोखा हर किसी के हक में नहीं आता दोस्त यह भी उसी को मिलता है जिसने शिद्दत से रिश्ता निभाया हो",
    "तुम्हारे लिए वह कितनी ही ईमानदार क्यूँ ना हो, एक औरत को हमेशा पता होता है कि तुम्हारे बाद उसे किसे message करना है",
    "दिल के छालों को कोई शायरी कहे तो परवाह नहीं, तकलीफ तो तब होता है जब कोई वाह वाह वाह करता है",
    "लड़कों को जिस प्रेमिका पर यकीन का गुरुर होता है, वही प्रेमिका जाने से पहले सब सुबूत मिटाने को कहती है.",
    "अगर धोखा देने के बाद भी एक प्रेमिका इज्जतदार है मतलब एक इज्जतदार प्रेमिका ने अपना मुँह नहीं खोला.",
    "मुझसे न मिल सकेगा किसी का मिजाज भी, मुझको तो अब गुलाब भी काले पसंद हैं",
    "पिता की जेब मे भले ही पैसे कम है. लेकिन मेरे लिए हमेशा वो बादशाह ही रहेंगे",
    "Stop acting like you hate relationship, Reality is : तुमने जिसे चाहा उसने तुम्हें नहीं चाहा.",
    "नींद भी उड़ जाती है दिलों की महफ़िल में, किसी को भूल कर सो जाना इतना आसान कहाँ...",
    "नसीब के बारे में क्या कहूँ, जो दिल ने चाहा वो कभी मिला ही नहीं...",
    "बेवफा ही नहीं बेरहम भी हो तुम, Jindagi tabah Karke Kahate Ho ki jao ab khush raho tum.",
    "Sach Sach batana पूरी कोशिश कर रहे हो ना उसे भुलाने की।",
    "Mohabbat mein jhukna koi buri baat nahi, suraj bhi dhalta hai chand ke liye.",
    "Waqt ne sikhaya hai ki har koi apna nahi hota.",
    "Tumhara naam hi kafi hai mere chehre par muskurahat lane ke liye.",
    "ये जिस जगह लाकर तुमने छोड़ा है, तमाम उम्र निकल जायेगी यहाँ से निकलने में..",
    "अरे aapko to इज़्ज़त krni chahiye thi is खामोशी ki..! Hm to iske phichhe aapki औकात छिपाये baithe the..!!"
];
