const allShayari = [
    // --- Nayi Shayari Sabse Upar Yahan Likhein ---
    

    // --- Aapka Purana Sara Data Niche Hai ---
"Teri khamoshi mein bhi ek sukoon sa milta hai, ye dil ab bas tere hi khayalon mein khilta hai.",
"Zindagi ki har raah par tera saath chahiye mujhe bas teri baahon ka mehakta sa hath chahiye.",
"Mohabbat ka rang kuch aise chadha hai tum par ab har dua mein bas tera hi naam rehta hai lab par.",
"Tunhe sochna hi ek ibadat si ban gayi hai ab toh bas tumhe chahna hi meri aadat si ban gayi hai.",
"Kuch khas nahi bas itni si tamanna hai ki tere dil ke kone mein mera ek chota sa thikano hai.",
"Humne toh dil lagaya tha sukoon ki talash mein par dard hi naseeb hua teri har yaad ke libas mein.",
"Toot kar bikhar gaye hain kuch is tarah se hum ki ab khud ko sametne ka hausla bhi nahi raha.",
"Unhone toh keh diya ki bhool jao humein par unhe kya pata ki unki yaadon se hi hum zinda hain.",
"Khamosh chehre par hazar pehre hote hain ye duniya nahi samajhti ki zakham kitne gehre hote hain.",
"Mo jo kehte the ki kabhi na chhodenge sath tera aaj unke hi shehar mein hum ajnabi ban gaye.",
"Dosti wo nahi jo sirf khushi mein sath de dosti toh wo hai jo har mushkil mein hath de.",
"Duniya ki bheed mein khud ko akela na samajhna tera yaar hai tere sath, kabhi mujhse door na rehna.",
"Suna hai dosti ka rishta sabse bada hota hai isliye toh ye dil tere liye har waqt khada hota hai.",
"Log kehte hain ki dosti mein dard milta hai hum toh kehte hain dosti mein hi jeene ka mard milta hai.",
"Lakho dost mil jayenge is jahan mein par teri jaisi dosti ki baat hi kuch aur hai.",
"Hum wo nahi jo waqt ke sath badal jayein hum toh wo hain jo waqt ko hi badal dete hain.",
"Meri fitrat mein nahi unke piche chalna jinhe aadat hai sirf dusron ke dan par uchhalna.",
"Log jalte hain meri kamyabi se dekh kar par unhe kya pata ki humne kante chune hain raaste par.",
"Sher apni taqat se raja banta hai aur hum apni mehnat se apni pehchan banate hain.",
"Raaste mushkil hain manzil par nazar hai meri himmat hi mera sabse bada humsafar hai.",
"Beshak tum ja chuke ho, par tumhara naam aaj bhi, mere dil ki dhadkan tez kar deta hai.#sad",
"Are aapko to izzat karni chahiye thi is khamoshi ki..! Hm to iske phichhe aapki aukat chipaye baithe the..!!#sad",
"Mere pass Aana to Waqt nikal kar aane Kyunki mere pass baten bahut hain aur sunane wale koi nhi.#sad",
"Kuchh logon Ne Hamen Aise samay per chhoda Diya..! Jab Ham Kisi Se Unki wafadari ki baten kar rahe the..!!#sad",
"Khatm kar diya unhone bhi Is Rishte jinhone Jindagi Bhar Sath nibhaane ke vade kiye the.#sad",
"Bichhadne ki jaldi unhen thi Aur Ilzam Sara Ham per Lagaya Gaya.#bewafa#sad",
"Safar tumhare sath Chhota Raha lekin Jindagi Bhar Ke Liye Sabak ban gaya.#sad#love",
"Shant chehron Ke Piche Aksar ghav Gehra Hote Hain.#sad",
"Uski Khushi Ke Liye use to Chhod Diya Maine per meri Khushiyan bhi Usi ke sath Chali gai.#sad#love",
"Yah bhul gaye Hamen Kisi Ki Khatir To Kya Hua Ham bhi to Unki Khatir Jamana bhulaye Baithe the.#love#sad",
"Jao Maaf Kiya Tumhen Aane Wale Waqt Mein Khuda Tumhare bete Ko Tumhare Jaisi Ladki Se Bachaye.#sad#love",
"Hamen to kab se Pata Tha Ki Tum Bewafa Ho Tumhen Chaha isliye ki Shayad Tumhari fitrat Badal Jaaye.#love#sad#bewafa",
"Unhen Mil Hi Jaate Hain Koi Na Koi jinhen achhe kirdar nahin sirf kiraedar chahiye hote Hain.#sad",
"Kabhi Maaf nahin kar Paunga usko Jisne bewajah meri Jindagi ko nahn-nahan karke rakh Diya.#sad#love",
"Ek din khatm ho hi Jaenge ya to Gam nhi to FIR ham.#sad",
"Jindagi Mein Ek Aisa Insan Jarur Hona chahiye Jo HAL Puche To Sach bataya Ja sake.#sad#love",
"Ek Din tumhare Karam Tumse milane aayenge Meri Jaan Rus use Din Tumhara Mat Hona.#sad#love",
"Rewafa hi nahi berham bhi ho tum Jindagi tabah Karke Kahate Ho ki jao ab khush raho tum.#sad#love",
"Tum apna Charitra Kitna bhi saaf Rakh Lo lekin chhodane wala Koi Na Koi Galti nikal hi dega.#sad",
"Kya fayda ab nishaniyan Dekhkar Rone se Jab Sath the tab Kadar Ki Na Gai.#sad",
"Yah Mujhse Ek Ladki Nahin Bulai Jari aur log pata nahin Kaise Kah Dete Hain Ki 36 aaenge 36 Jaenge.#sad#love",
"Sach Sach batana Puri koshish kar rahe ho na use Bhulane ki.#sad#love",
"Wain Shayad ab Tumhari Soch Mein Bhi Nahin Aahun Aur Tu Mujhe lamha-lamha Yad hai.#sad#love",
"Kuchh pal ke liye Laga tha ki Hamari Kahani bhi Shaadi Tak pahunchegi Pal Bhar Mein Sab tabah Kar Diya Usne Kisi Aur Ke liye.#sad#love",
"Pal Bhar Ke liye Chaha tha unhen Sath aur Hamen Laga Jindagi Bhar Ke Liye Humsafar Mil Gaya.#sad#love",
"Kahana To Nahin chahiye per kasam se bahut Pareshan hun Kahin Kuchh kar na lun To Maaf Karna.",
"Main mahsus nahin hui unhen hamari takleef jo kabhi kahte the ki ham tumhen tumse jyada jante hain.#sad#love",
"Unhen Chahat hi nahin Thi Kabhi Hamari unhen to hamari sirf jarurat thi.",
"Pahli bar kisi Se Pyar hua tha aur vahi Bewafa nikal gai.",
"Hans kar Bhul Jaate Hain sari baten iska matlab yah Nahin ki baten Hamare Dil per Nahin Lagti.",
"Tere Jaane ka itna Dukh Nahin Dukh to sirf is baat ka hai Ki Itna Pyar karne ke bad Bhi To Bewafa nikal gai.",
"Tum Nahin Laga paoge andaza Meri tabahi ka Tunne Sham Hone ke bad Mujhe Dekha hi kahan hai.",
"Na tumne kabhi samjha aur na samjhaya gaya vahi to main pagal chahta hi kya tha tumse tumhare alava.",
"Pahle sirf darr tha ki kahin kho na dun tumhe ab sirf gila hai ki kyun mile tum",
"Bas itni si dua hai ki jise tum chaho wo tumhein kabhi na chhode",
"Dard dene se pehle ek baar soch to liya hota... ki fir dard dene ke liye hum hi bache hain ya nahi",
"Tute hain, socha nahi tha, itna samay laga sab thik hone mein, ab fir se sab bikhar gaya.",
"Jo log sachai se mohabbat karte hain unhe aksar mohabbat sachi nahi milti.",
"Har baar bhul jata hoon use, par tera mujhe ek ek lafz yaad hai.",
"Pata nahi kya tha tum mein, mera sab kuch hi to tumhara tha.",
"Kisi ke feelings ke sath itna bhi mat khelo ki wo fir kabhi kisi par bharosa hi na kar paye",
"Mahadev, pls help me. Before, I do something wrong to myself.",
"Zindagi mein sab kuch mil jayega... lekin wo insan nahi jo tumhein khone se darta ho.", 

];
